
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 17 2025 17:21:47 IST (Dec 17 2025 11:51:47 UTC)

// Verification Directory fv/Low_area_ALU 

module Low_area_ALU(A, B, opt, load, clk, rst, Dout, done, SE, scan_in,
     scan_out);
  input [7:0] A, B;
  input [2:0] opt;
  input load, clk, rst, SE, scan_in;
  output [7:0] Dout;
  output done, scan_out;
  wire [7:0] A, B;
  wire [2:0] opt;
  wire load, clk, rst, SE, scan_in;
  wire [7:0] Dout;
  wire done, scan_out;
  wire [7:0] x;
  wire [7:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_100, n_101, n_102, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_119, n_120, n_121, n_123, n_124, n_125;
  wire n_126;
  assign done = 1'b1;
  OAI222XL g3053__2398(.A0 (n_97), .A1 (n_117), .B0 (opt[2]), .B1
       (n_126), .C0 (n_33), .C1 (n_49), .Y (Dout[7]));
  OAI222XL g3054__5107(.A0 (opt[1]), .A1 (n_55), .B0 (n_125), .B1
       (n_124), .C0 (n_96), .C1 (n_121), .Y (Dout[0]));
  OAI31X1 g3056__6260(.A0 (n_125), .A1 (x[7]), .A2 (scan_out), .B0
       (n_123), .Y (n_126));
  AOI21XL g3058__4319(.A0 (n_114), .A1 (n_56), .B0 (n_120), .Y (n_124));
  AOI22X1 g3057__8428(.A0 (n_125), .A1 (n_119), .B0 (n_107), .B1 (n_1),
       .Y (n_123));
  OAI221XL g3055__5526(.A0 (opt[2]), .A1 (n_116), .B0 (n_121), .B1
       (n_75), .C0 (n_76), .Y (Dout[6]));
  NOR2XL g3059__6783(.A (n_53), .B (n_119), .Y (n_120));
  OAI211XL g3060__3680(.A0 (n_117), .A1 (n_121), .B0 (n_71), .C0
       (n_115), .Y (Dout[5]));
  OAI21X1 g3063__1617(.A0 (n_112), .A1 (n_111), .B0 (n_113), .Y
       (n_119));
  OAI211X1 g3061__2802(.A0 (opt[1]), .A1 (n_110), .B0 (n_42), .C0
       (n_30), .Y (n_116));
  AOI32XL g3062__1705(.A0 (n_93), .A1 (n_108), .A2 (n_15), .B0 (n_114),
       .B1 (n_109), .Y (n_115));
  NAND2XL g3064__5122(.A (n_112), .B (n_111), .Y (n_113));
  ADDFX1 g3065__8246(.A (n_34), .B (x[6]), .CI (n_104), .CO (n_111), .S
       (n_110));
  AOI222XL g3067__7098(.A0 (n_108), .A1 (n_107), .B0 (opt[1]), .B1
       (n_14), .C0 (n_125), .C1 (n_106), .Y (n_109));
  INVXL g3068(.A (n_105), .Y (n_106));
  ADDFX1 g3069__6131(.A (n_37), .B (x[5]), .CI (n_100), .CO (n_104), .S
       (n_105));
  OAI211XL g3066__1881(.A0 (n_102), .A1 (opt[2]), .B0 (n_81), .C0
       (n_73), .Y (Dout[4]));
  OAI211X1 g3071__5115(.A0 (opt[1]), .A1 (n_101), .B0 (n_48), .C0
       (n_32), .Y (n_102));
  ADDFX1 g3072__7482(.A (n_35), .B (x[4]), .CI (n_91), .CO (n_100), .S
       (n_101));
  OAI211XL g3070__4733(.A0 (n_95), .A1 (opt[2]), .B0 (n_80), .C0
       (n_74), .Y (Dout[3]));
  OAI221XL g3073__6161(.A0 (n_121), .A1 (n_0), .B0 (n_97), .B1 (n_96),
       .C0 (n_94), .Y (Dout[2]));
  OAI211X1 g3074__9315(.A0 (opt[1]), .A1 (n_92), .B0 (n_46), .C0
       (n_29), .Y (n_95));
  AOI32XL g3075__9945(.A0 (n_93), .A1 (n_89), .A2 (n_18), .B0 (n_114),
       .B1 (n_90), .Y (n_94));
  ADDFX1 g3076__2883(.A (n_40), .B (x[3]), .CI (n_86), .CO (n_91), .S
       (n_92));
  AOI222XL g3078__2346(.A0 (n_89), .A1 (n_107), .B0 (opt[1]), .B1
       (n_17), .C0 (n_125), .C1 (n_88), .Y (n_90));
  INVXL g3079(.A (n_87), .Y (n_88));
  ADDFX1 g3080__1666(.A (n_38), .B (x[2]), .CI (n_82), .CO (n_86), .S
       (n_87));
  OAI211XL g3077__7410(.A0 (n_84), .A1 (opt[2]), .B0 (n_77), .C0
       (n_72), .Y (Dout[1]));
  OAI211X1 g3081__6417(.A0 (opt[1]), .A1 (n_83), .B0 (n_44), .C0
       (n_27), .Y (n_84));
  ADDFX1 g3082__5477(.A (n_25), .B (x[1]), .CI (n_24), .CO (n_82), .S
       (n_83));
  SDFFQX1 \y_reg[2] (.CK (clk), .D (n_60), .SI (y[1]), .SE (SE), .Q
       (y[2]));
  SDFFQX1 \y_reg[0] (.CK (clk), .D (n_62), .SI (x[7]), .SE (SE), .Q
       (y[0]));
  SDFFQX1 \y_reg[1] (.CK (clk), .D (n_59), .SI (y[0]), .SE (SE), .Q
       (y[1]));
  SDFFQX1 \y_reg[3] (.CK (clk), .D (n_61), .SI (y[2]), .SE (SE), .Q
       (y[3]));
  SDFFQX1 \y_reg[6] (.CK (clk), .D (n_67), .SI (y[5]), .SE (SE), .Q
       (y[6]));
  SDFFQX1 \x_reg[6] (.CK (clk), .D (n_63), .SI (x[5]), .SE (SE), .Q
       (x[6]));
  SDFFQX1 \x_reg[2] (.CK (clk), .D (n_51), .SI (x[1]), .SE (SE), .Q
       (x[2]));
  SDFFQX1 \x_reg[3] (.CK (clk), .D (n_66), .SI (x[2]), .SE (SE), .Q
       (x[3]));
  SDFFQX1 \x_reg[5] (.CK (clk), .D (n_70), .SI (x[4]), .SE (SE), .Q
       (x[5]));
  AOI22X1 g3093__2398(.A0 (n_79), .A1 (x[5]), .B0 (n_78), .B1 (x[3]),
       .Y (n_81));
  AOI22X1 g3094__5107(.A0 (n_79), .A1 (x[4]), .B0 (n_78), .B1 (x[2]),
       .Y (n_80));
  AOI22X1 g3095__6260(.A0 (n_79), .A1 (x[2]), .B0 (n_78), .B1 (x[0]),
       .Y (n_77));
  SDFFQX1 \y_reg[4] (.CK (clk), .D (n_58), .SI (y[3]), .SE (SE), .Q
       (y[4]));
  SDFFQX1 \y_reg[5] (.CK (clk), .D (n_50), .SI (y[4]), .SE (SE), .Q
       (y[5]));
  SDFFQX1 \x_reg[0] (.CK (clk), .D (n_64), .SI (scan_in), .SE (SE), .Q
       (x[0]));
  SDFFQX1 \y_reg[7] (.CK (clk), .D (n_57), .SI (y[6]), .SE (SE), .Q
       (scan_out));
  SDFFQX1 \x_reg[1] (.CK (clk), .D (n_69), .SI (x[0]), .SE (SE), .Q
       (x[1]));
  SDFFQX1 \x_reg[4] (.CK (clk), .D (n_65), .SI (x[3]), .SE (SE), .Q
       (x[4]));
  SDFFQX1 \x_reg[7] (.CK (clk), .D (n_68), .SI (x[6]), .SE (SE), .Q
       (x[7]));
  AOI32X1 g3096__4319(.A0 (n_93), .A1 (n_41), .A2 (n_20), .B0 (n_78),
       .B1 (x[5]), .Y (n_76));
  MXI2XL g3097__8428(.A (n_75), .B (x[7]), .S0 (n_36), .Y (n_112));
  NAND3BXL g3123__5526(.AN (n_28), .B (n_93), .C (n_45), .Y (n_74));
  NAND3BXL g3124__6783(.AN (n_31), .B (n_93), .C (n_47), .Y (n_73));
  NAND3BXL g3125__3680(.AN (n_26), .B (n_93), .C (n_43), .Y (n_72));
  NAND2XL g3109__1617(.A (n_78), .B (x[4]), .Y (n_71));
  CLKINVX1 g3126(.A (n_121), .Y (n_79));
  NOR2XL g3107__2802(.A (rst), .B (n_10), .Y (n_70));
  NOR2XL g3118__1705(.A (rst), .B (n_22), .Y (n_69));
  NOR2XL g3104__5122(.A (rst), .B (n_3), .Y (n_68));
  NOR2XL g3114__8246(.A (rst), .B (n_6), .Y (n_67));
  NOR2XL g3105__7098(.A (rst), .B (n_16), .Y (n_66));
  NOR2XL g3106__6131(.A (rst), .B (n_2), .Y (n_65));
  NOR2XL g3117__1881(.A (rst), .B (n_12), .Y (n_64));
  NOR2XL g3108__5115(.A (rst), .B (n_23), .Y (n_63));
  NOR2XL g3110__7482(.A (rst), .B (n_9), .Y (n_62));
  NOR2XL g3111__4733(.A (rst), .B (n_21), .Y (n_61));
  NOR2XL g3112__6161(.A (rst), .B (n_4), .Y (n_60));
  NOR2XL g3113__9315(.A (rst), .B (n_13), .Y (n_59));
  NOR2XL g3119__9945(.A (rst), .B (n_11), .Y (n_58));
  NOR2XL g3120__2883(.A (rst), .B (n_5), .Y (n_57));
  OAI21XL g3121__2346(.A0 (n_39), .A1 (n_54), .B0 (n_52), .Y (n_56));
  NAND3BXL g3122__1666(.AN (n_54), .B (n_53), .C (n_52), .Y (n_55));
  NOR2XL g3115__7410(.A (rst), .B (n_8), .Y (n_51));
  NOR2XL g3116__6417(.A (rst), .B (n_7), .Y (n_50));
  INVXL g3128(.A (n_93), .Y (n_49));
  NAND2XL g3130__5477(.A (n_107), .B (n_47), .Y (n_48));
  NAND2XL g3132__2398(.A (n_107), .B (n_45), .Y (n_46));
  NAND2XL g3134__5107(.A (n_107), .B (n_43), .Y (n_44));
  NAND2XL g3135__6260(.A (n_107), .B (n_41), .Y (n_42));
  CLKINVX1 g3127(.A (n_78), .Y (n_97));
  NAND2XL g3144__4319(.A (opt[2]), .B (n_107), .Y (n_121));
  MXI2XL g3163__8428(.A (n_39), .B (opt[0]), .S0 (y[3]), .Y (n_40));
  MXI2XL g3158__5526(.A (n_39), .B (opt[0]), .S0 (y[2]), .Y (n_38));
  MXI2XL g3159__6783(.A (n_39), .B (opt[0]), .S0 (y[5]), .Y (n_37));
  MXI2XL g3160__3680(.A (n_39), .B (opt[0]), .S0 (scan_out), .Y (n_36));
  MXI2XL g3161__1617(.A (n_39), .B (opt[0]), .S0 (y[4]), .Y (n_35));
  MXI2XL g3162__2802(.A (n_39), .B (opt[0]), .S0 (y[6]), .Y (n_34));
  MXI2XL g3157__1705(.A (x[7]), .B (n_75), .S0 (scan_out), .Y (n_33));
  NAND2XL g3136__5122(.A (opt[1]), .B (n_31), .Y (n_32));
  NAND2XL g3129__8246(.A (opt[1]), .B (n_19), .Y (n_30));
  NAND2XL g3131__7098(.A (opt[1]), .B (n_28), .Y (n_29));
  NAND2XL g3133__6131(.A (opt[1]), .B (n_26), .Y (n_27));
  MXI2XL g3164__1881(.A (n_39), .B (opt[0]), .S0 (y[1]), .Y (n_25));
  OAI21X1 g3143__5115(.A0 (n_39), .A1 (y[0]), .B0 (n_52), .Y (n_24));
  NOR2XL g3145__7482(.A (opt[1]), .B (n_53), .Y (n_78));
  NOR3X1 g3146__4733(.A (opt[0]), .B (opt[1]), .C (n_114), .Y (n_93));
  MXI2XL g3154__6161(.A (x[6]), .B (A[6]), .S0 (load), .Y (n_23));
  MXI2XL g3155__9315(.A (x[1]), .B (A[1]), .S0 (load), .Y (n_22));
  MXI2XL g3156__9945(.A (y[3]), .B (B[3]), .S0 (load), .Y (n_21));
  INVXL g3173(.A (n_19), .Y (n_20));
  INVXL g3174(.A (n_17), .Y (n_18));
  MXI2XL g3139__2883(.A (x[3]), .B (A[3]), .S0 (load), .Y (n_16));
  INVXL g3175(.A (n_14), .Y (n_15));
  MXI2XL g3137__2346(.A (y[1]), .B (B[1]), .S0 (load), .Y (n_13));
  MXI2XL g3138__1666(.A (x[0]), .B (A[0]), .S0 (load), .Y (n_12));
  NOR2XL g3184__7410(.A (opt[0]), .B (n_125), .Y (n_107));
  MXI2XL g3140__6417(.A (y[4]), .B (B[4]), .S0 (load), .Y (n_11));
  MXI2XL g3141__5477(.A (x[5]), .B (A[5]), .S0 (load), .Y (n_10));
  MXI2XL g3142__2398(.A (y[0]), .B (B[0]), .S0 (load), .Y (n_9));
  MXI2XL g3147__5107(.A (x[2]), .B (A[2]), .S0 (load), .Y (n_8));
  MXI2XL g3148__6260(.A (y[5]), .B (B[5]), .S0 (load), .Y (n_7));
  MXI2XL g3149__4319(.A (y[6]), .B (B[6]), .S0 (load), .Y (n_6));
  MXI2XL g3150__8428(.A (scan_out), .B (B[7]), .S0 (load), .Y (n_5));
  MXI2XL g3151__5526(.A (y[2]), .B (B[2]), .S0 (load), .Y (n_4));
  MXI2XL g3152__6783(.A (x[7]), .B (A[7]), .S0 (load), .Y (n_3));
  MXI2XL g3153__3680(.A (x[4]), .B (A[4]), .S0 (load), .Y (n_2));
  NAND2XL g3176__1617(.A (x[7]), .B (scan_out), .Y (n_1));
  NAND2XL g3168__2802(.A (x[6]), .B (y[6]), .Y (n_41));
  NOR2XL g3170__1705(.A (x[3]), .B (y[3]), .Y (n_28));
  NAND2XL g3166__5122(.A (x[1]), .B (y[1]), .Y (n_43));
  NOR2XL g3177__8246(.A (x[6]), .B (y[6]), .Y (n_19));
  NOR2XL g3178__7098(.A (x[0]), .B (y[0]), .Y (n_54));
  NOR2XL g3180__6131(.A (x[2]), .B (y[2]), .Y (n_17));
  NAND2XL g3172__1881(.A (x[0]), .B (y[0]), .Y (n_52));
  NAND2XL g3179__5115(.A (x[5]), .B (y[5]), .Y (n_108));
  NAND2XL g3167__7482(.A (x[4]), .B (y[4]), .Y (n_47));
  NAND2XL g3171__4733(.A (x[3]), .B (y[3]), .Y (n_45));
  NOR2XL g3181__6161(.A (x[5]), .B (y[5]), .Y (n_14));
  NOR2XL g3169__9315(.A (x[1]), .B (y[1]), .Y (n_26));
  NOR2XL g3165__9945(.A (x[4]), .B (y[4]), .Y (n_31));
  NAND2XL g3182__2883(.A (x[2]), .B (y[2]), .Y (n_89));
  NAND2XL g3183__2346(.A (opt[0]), .B (opt[2]), .Y (n_53));
  INVXL g3189(.A (x[3]), .Y (n_0));
  CLKINVX1 g3186(.A (x[7]), .Y (n_75));
  CLKINVX1 g3188(.A (opt[0]), .Y (n_39));
  CLKINVX1 g3185(.A (x[6]), .Y (n_117));
  CLKINVX1 g3190(.A (x[1]), .Y (n_96));
  CLKINVX1 g3187(.A (opt[2]), .Y (n_114));
  CLKINVX1 g3191(.A (opt[1]), .Y (n_125));
endmodule

